local exec = hl.dsp.exec_cmd
hl.bind('SUPER + RETURN', exec('kitty'))
hl.bind('SUPER + Q', hl.dsp.window.close())
hl.bind('SUPER + SPACE', exec('qs ipc call hyprx launcher'))
hl.bind('SUPER + C', exec('qs ipc call hyprx control'))
hl.bind('SUPER + E', exec('qs ipc call hyprx files'))
hl.bind('SUPER + V', exec('qs ipc call hyprx clipboard'))
hl.bind('SUPER + W', exec('qs ipc call hyprx wallpaper'))
hl.bind('SUPER + SHIFT + W', exec('hyprx-wallpaper --random'))
hl.bind('XF86AudioRaiseVolume', exec('wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%+'), { locked=true, repeating=true })
hl.bind('XF86AudioLowerVolume', exec('wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-'), { locked=true, repeating=true })
hl.bind('XF86AudioMute', exec('wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'), { locked=true })
hl.bind('XF86MonBrightnessUp', exec('brightnessctl set +5%'), { locked=true, repeating=true })
hl.bind('XF86MonBrightnessDown', exec('brightnessctl set 5%-'), { locked=true, repeating=true })
