hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("hyprpolkitagent")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("qs -c hyprx")
    hl.exec_cmd("hyprx-restore-wallpaper")
end)
